// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZSEeg3nuCQfcF1ZSb5hbwYjqdSKn3VdY',
    appId: '1:944564058193:web:398409aa882015daeca070',
    messagingSenderId: '944564058193',
    projectId: 'ihapp-183f6',
    authDomain: 'ihapp-183f6.firebaseapp.com',
    storageBucket: 'ihapp-183f6.appspot.com',
    measurementId: 'G-PCNBESYHK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKipgc3FOxa0-06QOKoPYbDl7FLq-VuGM',
    appId: '1:944564058193:android:bd0d140a8a3222adeca070',
    messagingSenderId: '944564058193',
    projectId: 'ihapp-183f6',
    storageBucket: 'ihapp-183f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7uarf_rHcnDrwA_M_UtRI0QIUS222sq8',
    appId: '1:944564058193:ios:fb7ee277a08dbd9aeca070',
    messagingSenderId: '944564058193',
    projectId: 'ihapp-183f6',
    storageBucket: 'ihapp-183f6.appspot.com',
    iosClientId: '944564058193-aqq8noh1uh58kn3uncl6rhnm51mp4gpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ihapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7uarf_rHcnDrwA_M_UtRI0QIUS222sq8',
    appId: '1:944564058193:ios:fb7ee277a08dbd9aeca070',
    messagingSenderId: '944564058193',
    projectId: 'ihapp-183f6',
    storageBucket: 'ihapp-183f6.appspot.com',
    iosClientId: '944564058193-aqq8noh1uh58kn3uncl6rhnm51mp4gpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ihapp',
  );
}
